ci:
  skip: [cmake-build]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: double-quote-string-fixer
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v13.0.1'
    hooks:
      - id: clang-format
  - repo: https://github.com/dead-tech/pre-commit-cmake
    rev: 'v0.0.3'
    hooks:
      - id: cmake-build
