[book]
title = "argparse-cpp Documentation"
description = "Argument Parser in C++ inspired by python's argparse module"
authors = ["Luca Natilla"]
language = "en"

[output.html]
git-repository-url = "https://github.com/dead-tech/argparse-cpp"
no-section-label = true
