name: Build (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Conan
        id: conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Conan Version
        run: echo "${{ steps.conan.outputs.version}}"
      - name: Get Latest G++/GCC version
        run: sudo apt install gcc-11 g++-11
      - name: Set CXX=g++-11
        run: echo "CXX=g++-11" >> $GITHUB_ENV
      - name: Set CC=gcc-11
        run: echo "CC=gcc-11" >> $GITHUB_ENV
      - name: Create conan default profile
        run: conan profile new default --detect
      - name: Update conan profile
        run: conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Install conan dependencies
        run: conan install . -s build_type=${{env.BUILD_TYPE}} --install-folder=${{github.workspace}}/build
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
